/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ApiKeysApi,
  BillingApi,
  BrowsersApi,
  OpenAPIApi,
  ServerApi,
  UsageApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BrowserCatCustom } from "./client-custom";

export class BrowserCat extends BrowserCatCustom {
  readonly apiKeys: ApiKeysApi;
  readonly billing: BillingApi;
  readonly browsers: BrowsersApi;
  readonly openAPI: OpenAPIApi;
  readonly server: ServerApi;
  readonly usage: UsageApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.apiKeys = new ApiKeysApi(configuration);
    this.billing = new BillingApi(configuration);
    this.browsers = new BrowsersApi(configuration);
    this.openAPI = new OpenAPIApi(configuration);
    this.server = new ServerApi(configuration);
    this.usage = new UsageApi(configuration);
  }

}
