/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysGetKey403Response
 */
export interface ApiKeysGetKey403Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysGetKey403Response
     */
    'status': ApiKeysGetKey403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysGetKey403Response
     */
    'error': ApiKeysGetKey403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysGetKey403Response
     */
    'message': string;
}

type ApiKeysGetKey403ResponseStatusEnum = 403
type ApiKeysGetKey403ResponseErrorEnum = 'Forbidden'


