/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface ApiKeysRevokeKeyResponse
 */
export interface ApiKeysRevokeKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysRevokeKeyResponse
     */
    'status': ApiKeysRevokeKeyResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysRevokeKeyResponse
     */
    'error': ApiKeysRevokeKeyResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysRevokeKeyResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof ApiKeysRevokeKeyResponse
     */
    'invalid'?: ApiKeysRevokeKeyResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof ApiKeysRevokeKeyResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type ApiKeysRevokeKeyResponseStatusEnum = 400
type ApiKeysRevokeKeyResponseErrorEnum = 'Bad Request'
type ApiKeysRevokeKeyResponseInvalidEnum = 'body' | 'path' | 'query'


