/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysRevokeKey401Response
 */
export interface ApiKeysRevokeKey401Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysRevokeKey401Response
     */
    'status': ApiKeysRevokeKey401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysRevokeKey401Response
     */
    'error': ApiKeysRevokeKey401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysRevokeKey401Response
     */
    'message': string;
}

type ApiKeysRevokeKey401ResponseStatusEnum = 401
type ApiKeysRevokeKey401ResponseErrorEnum = 'Unauthorized'


