/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysUpdateKey500Response
 */
export interface ApiKeysUpdateKey500Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateKey500Response
     */
    'status': ApiKeysUpdateKey500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateKey500Response
     */
    'error': ApiKeysUpdateKey500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateKey500Response
     */
    'message': string;
}

type ApiKeysUpdateKey500ResponseStatusEnum = 500
type ApiKeysUpdateKey500ResponseErrorEnum = 'Internal Server Error'


