/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysRevokeKey403Response
 */
export interface ApiKeysRevokeKey403Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysRevokeKey403Response
     */
    'status': ApiKeysRevokeKey403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysRevokeKey403Response
     */
    'error': ApiKeysRevokeKey403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysRevokeKey403Response
     */
    'message': string;
}

type ApiKeysRevokeKey403ResponseStatusEnum = 403
type ApiKeysRevokeKey403ResponseErrorEnum = 'Forbidden'


