/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysRevokeKey500Response
 */
export interface ApiKeysRevokeKey500Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysRevokeKey500Response
     */
    'status': ApiKeysRevokeKey500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysRevokeKey500Response
     */
    'error': ApiKeysRevokeKey500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysRevokeKey500Response
     */
    'message': string;
}

type ApiKeysRevokeKey500ResponseStatusEnum = 500
type ApiKeysRevokeKey500ResponseErrorEnum = 'Internal Server Error'


