/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysListAll403Response
 */
export interface ApiKeysListAll403Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysListAll403Response
     */
    'status': ApiKeysListAll403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysListAll403Response
     */
    'error': ApiKeysListAll403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysListAll403Response
     */
    'message': string;
}

type ApiKeysListAll403ResponseStatusEnum = 403
type ApiKeysListAll403ResponseErrorEnum = 'Forbidden'


