/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface ApiKeysUpdateKeyResponse
 */
export interface ApiKeysUpdateKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateKeyResponse
     */
    'status': ApiKeysUpdateKeyResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateKeyResponse
     */
    'error': ApiKeysUpdateKeyResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateKeyResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof ApiKeysUpdateKeyResponse
     */
    'invalid'?: ApiKeysUpdateKeyResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof ApiKeysUpdateKeyResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type ApiKeysUpdateKeyResponseStatusEnum = 400
type ApiKeysUpdateKeyResponseErrorEnum = 'Bad Request'
type ApiKeysUpdateKeyResponseInvalidEnum = 'body' | 'path' | 'query'


