/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysGetKey500Response
 */
export interface ApiKeysGetKey500Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysGetKey500Response
     */
    'status': ApiKeysGetKey500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysGetKey500Response
     */
    'error': ApiKeysGetKey500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysGetKey500Response
     */
    'message': string;
}

type ApiKeysGetKey500ResponseStatusEnum = 500
type ApiKeysGetKey500ResponseErrorEnum = 'Internal Server Error'


