/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysCreateApiKey403Response
 */
export interface ApiKeysCreateApiKey403Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysCreateApiKey403Response
     */
    'status': ApiKeysCreateApiKey403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysCreateApiKey403Response
     */
    'error': ApiKeysCreateApiKey403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysCreateApiKey403Response
     */
    'message': string;
}

type ApiKeysCreateApiKey403ResponseStatusEnum = 403
type ApiKeysCreateApiKey403ResponseErrorEnum = 'Forbidden'


