/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysRevokeKey404Response
 */
export interface ApiKeysRevokeKey404Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysRevokeKey404Response
     */
    'status': ApiKeysRevokeKey404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysRevokeKey404Response
     */
    'error': ApiKeysRevokeKey404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysRevokeKey404Response
     */
    'message': string;
}

type ApiKeysRevokeKey404ResponseStatusEnum = 404
type ApiKeysRevokeKey404ResponseErrorEnum = 'Not Found'


