/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface ApiKeysGetKeyResponse
 */
export interface ApiKeysGetKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysGetKeyResponse
     */
    'status': ApiKeysGetKeyResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysGetKeyResponse
     */
    'error': ApiKeysGetKeyResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysGetKeyResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof ApiKeysGetKeyResponse
     */
    'invalid'?: ApiKeysGetKeyResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof ApiKeysGetKeyResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type ApiKeysGetKeyResponseStatusEnum = 400
type ApiKeysGetKeyResponseErrorEnum = 'Bad Request'
type ApiKeysGetKeyResponseInvalidEnum = 'body' | 'path' | 'query'


