/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface ApiKeysCreateApiKeyResponse
 */
export interface ApiKeysCreateApiKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysCreateApiKeyResponse
     */
    'status': ApiKeysCreateApiKeyResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysCreateApiKeyResponse
     */
    'error': ApiKeysCreateApiKeyResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysCreateApiKeyResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof ApiKeysCreateApiKeyResponse
     */
    'invalid'?: ApiKeysCreateApiKeyResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof ApiKeysCreateApiKeyResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type ApiKeysCreateApiKeyResponseStatusEnum = 400
type ApiKeysCreateApiKeyResponseErrorEnum = 'Bad Request'
type ApiKeysCreateApiKeyResponseInvalidEnum = 'body' | 'path' | 'query'


