/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysUpdateKey404Response
 */
export interface ApiKeysUpdateKey404Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateKey404Response
     */
    'status': ApiKeysUpdateKey404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateKey404Response
     */
    'error': ApiKeysUpdateKey404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateKey404Response
     */
    'message': string;
}

type ApiKeysUpdateKey404ResponseStatusEnum = 404
type ApiKeysUpdateKey404ResponseErrorEnum = 'Not Found'


