/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysUpdateApiKey404Response
 */
export interface ApiKeysUpdateApiKey404Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateApiKey404Response
     */
    'status': ApiKeysUpdateApiKey404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateApiKey404Response
     */
    'error': ApiKeysUpdateApiKey404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateApiKey404Response
     */
    'message': string;
}

type ApiKeysUpdateApiKey404ResponseStatusEnum = 404
type ApiKeysUpdateApiKey404ResponseErrorEnum = 'Not Found'


