/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysCreateApiKey401Response
 */
export interface ApiKeysCreateApiKey401Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysCreateApiKey401Response
     */
    'status': ApiKeysCreateApiKey401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysCreateApiKey401Response
     */
    'error': ApiKeysCreateApiKey401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysCreateApiKey401Response
     */
    'message': string;
}

type ApiKeysCreateApiKey401ResponseStatusEnum = 401
type ApiKeysCreateApiKey401ResponseErrorEnum = 'Unauthorized'


