/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysListAll401Response
 */
export interface ApiKeysListAll401Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysListAll401Response
     */
    'status': ApiKeysListAll401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysListAll401Response
     */
    'error': ApiKeysListAll401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysListAll401Response
     */
    'message': string;
}

type ApiKeysListAll401ResponseStatusEnum = 401
type ApiKeysListAll401ResponseErrorEnum = 'Unauthorized'


