/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysUpdateApiKey401Response
 */
export interface ApiKeysUpdateApiKey401Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateApiKey401Response
     */
    'status': ApiKeysUpdateApiKey401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateApiKey401Response
     */
    'error': ApiKeysUpdateApiKey401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateApiKey401Response
     */
    'message': string;
}

type ApiKeysUpdateApiKey401ResponseStatusEnum = 401
type ApiKeysUpdateApiKey401ResponseErrorEnum = 'Unauthorized'


