/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeysUpdateApiKey500Response
 */
export interface ApiKeysUpdateApiKey500Response {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateApiKey500Response
     */
    'status': ApiKeysUpdateApiKey500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateApiKey500Response
     */
    'error': ApiKeysUpdateApiKey500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateApiKey500Response
     */
    'message': string;
}

type ApiKeysUpdateApiKey500ResponseStatusEnum = 500
type ApiKeysUpdateApiKey500ResponseErrorEnum = 'Internal Server Error'


