/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface ApiKeysUpdateApiKeyResponse
 */
export interface ApiKeysUpdateApiKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiKeysUpdateApiKeyResponse
     */
    'status': ApiKeysUpdateApiKeyResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysUpdateApiKeyResponse
     */
    'error': ApiKeysUpdateApiKeyResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ApiKeysUpdateApiKeyResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof ApiKeysUpdateApiKeyResponse
     */
    'invalid'?: ApiKeysUpdateApiKeyResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof ApiKeysUpdateApiKeyResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type ApiKeysUpdateApiKeyResponseStatusEnum = 400
type ApiKeysUpdateApiKeyResponseErrorEnum = 'Bad Request'
type ApiKeysUpdateApiKeyResponseInvalidEnum = 'body' | 'path' | 'query'


