/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface BadRequestError
 */
export interface BadRequestError {
    /**
     * 
     * @type {number}
     * @memberof BadRequestError
     */
    'status': BadRequestErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BadRequestError
     */
    'error': BadRequestErrorErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BadRequestError
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof BadRequestError
     */
    'invalid'?: BadRequestErrorInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof BadRequestError
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type BadRequestErrorStatusEnum = 400
type BadRequestErrorErrorEnum = 'Bad Request'
type BadRequestErrorInvalidEnum = 'body' | 'path' | 'query'


