/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInnerPathInner } from './bad-request-error-fields-inner-path-inner';

/**
 * 
 * @export
 * @interface BadRequestErrorFieldsInner
 */
export interface BadRequestErrorFieldsInner {
    /**
     * 
     * @type {string}
     * @memberof BadRequestErrorFieldsInner
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof BadRequestErrorFieldsInner
     */
    'expected'?: string;
    /**
     * 
     * @type {string}
     * @memberof BadRequestErrorFieldsInner
     */
    'received'?: string;
    /**
     * 
     * @type {string}
     * @memberof BadRequestErrorFieldsInner
     */
    'validation'?: string;
    /**
     * 
     * @type {Array<BadRequestErrorFieldsInnerPathInner>}
     * @memberof BadRequestErrorFieldsInner
     */
    'path': Array<BadRequestErrorFieldsInnerPathInner>;
    /**
     * 
     * @type {string}
     * @memberof BadRequestErrorFieldsInner
     */
    'message'?: string;
}

