/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingListSubscriptionsWithinRange500Response
 */
export interface BillingListSubscriptionsWithinRange500Response {
    /**
     * 
     * @type {number}
     * @memberof BillingListSubscriptionsWithinRange500Response
     */
    'status': BillingListSubscriptionsWithinRange500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingListSubscriptionsWithinRange500Response
     */
    'error': BillingListSubscriptionsWithinRange500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingListSubscriptionsWithinRange500Response
     */
    'message': string;
}

type BillingListSubscriptionsWithinRange500ResponseStatusEnum = 500
type BillingListSubscriptionsWithinRange500ResponseErrorEnum = 'Internal Server Error'


