/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetSpecificInvoice401Response
 */
export interface BillingGetSpecificInvoice401Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetSpecificInvoice401Response
     */
    'status': BillingGetSpecificInvoice401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetSpecificInvoice401Response
     */
    'error': BillingGetSpecificInvoice401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetSpecificInvoice401Response
     */
    'message': string;
}

type BillingGetSpecificInvoice401ResponseStatusEnum = 401
type BillingGetSpecificInvoice401ResponseErrorEnum = 'Unauthorized'


