/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface BillingGetActiveSubscriptionResponse
 */
export interface BillingGetActiveSubscriptionResponse {
    /**
     * 
     * @type {number}
     * @memberof BillingGetActiveSubscriptionResponse
     */
    'status': BillingGetActiveSubscriptionResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetActiveSubscriptionResponse
     */
    'error': BillingGetActiveSubscriptionResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetActiveSubscriptionResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof BillingGetActiveSubscriptionResponse
     */
    'invalid'?: BillingGetActiveSubscriptionResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof BillingGetActiveSubscriptionResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type BillingGetActiveSubscriptionResponseStatusEnum = 400
type BillingGetActiveSubscriptionResponseErrorEnum = 'Bad Request'
type BillingGetActiveSubscriptionResponseInvalidEnum = 'body' | 'path' | 'query'


