/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingListInvoicesRange401Response
 */
export interface BillingListInvoicesRange401Response {
    /**
     * 
     * @type {number}
     * @memberof BillingListInvoicesRange401Response
     */
    'status': BillingListInvoicesRange401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingListInvoicesRange401Response
     */
    'error': BillingListInvoicesRange401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingListInvoicesRange401Response
     */
    'message': string;
}

type BillingListInvoicesRange401ResponseStatusEnum = 401
type BillingListInvoicesRange401ResponseErrorEnum = 'Unauthorized'


