/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetActiveSubscription404Response
 */
export interface BillingGetActiveSubscription404Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetActiveSubscription404Response
     */
    'status': BillingGetActiveSubscription404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetActiveSubscription404Response
     */
    'error': BillingGetActiveSubscription404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetActiveSubscription404Response
     */
    'message': string;
}

type BillingGetActiveSubscription404ResponseStatusEnum = 404
type BillingGetActiveSubscription404ResponseErrorEnum = 'Not Found'


