/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetInvoicePdf403Response
 */
export interface BillingGetInvoicePdf403Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetInvoicePdf403Response
     */
    'status': BillingGetInvoicePdf403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetInvoicePdf403Response
     */
    'error': BillingGetInvoicePdf403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetInvoicePdf403Response
     */
    'message': string;
}

type BillingGetInvoicePdf403ResponseStatusEnum = 403
type BillingGetInvoicePdf403ResponseErrorEnum = 'Forbidden'


