/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetSpecificSubscription404Response
 */
export interface BillingGetSpecificSubscription404Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetSpecificSubscription404Response
     */
    'status': BillingGetSpecificSubscription404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetSpecificSubscription404Response
     */
    'error': BillingGetSpecificSubscription404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetSpecificSubscription404Response
     */
    'message': string;
}

type BillingGetSpecificSubscription404ResponseStatusEnum = 404
type BillingGetSpecificSubscription404ResponseErrorEnum = 'Not Found'


