/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetInvoicePdf401Response
 */
export interface BillingGetInvoicePdf401Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetInvoicePdf401Response
     */
    'status': BillingGetInvoicePdf401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetInvoicePdf401Response
     */
    'error': BillingGetInvoicePdf401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetInvoicePdf401Response
     */
    'message': string;
}

type BillingGetInvoicePdf401ResponseStatusEnum = 401
type BillingGetInvoicePdf401ResponseErrorEnum = 'Unauthorized'


