/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingListInvoicesRange500Response
 */
export interface BillingListInvoicesRange500Response {
    /**
     * 
     * @type {number}
     * @memberof BillingListInvoicesRange500Response
     */
    'status': BillingListInvoicesRange500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingListInvoicesRange500Response
     */
    'error': BillingListInvoicesRange500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingListInvoicesRange500Response
     */
    'message': string;
}

type BillingListInvoicesRange500ResponseStatusEnum = 500
type BillingListInvoicesRange500ResponseErrorEnum = 'Internal Server Error'


