/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface BillingListInvoicesRangeResponse
 */
export interface BillingListInvoicesRangeResponse {
    /**
     * 
     * @type {number}
     * @memberof BillingListInvoicesRangeResponse
     */
    'status': BillingListInvoicesRangeResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingListInvoicesRangeResponse
     */
    'error': BillingListInvoicesRangeResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingListInvoicesRangeResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof BillingListInvoicesRangeResponse
     */
    'invalid'?: BillingListInvoicesRangeResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof BillingListInvoicesRangeResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type BillingListInvoicesRangeResponseStatusEnum = 400
type BillingListInvoicesRangeResponseErrorEnum = 'Bad Request'
type BillingListInvoicesRangeResponseInvalidEnum = 'body' | 'path' | 'query'


