/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface BillingListSubscriptionsWithinRangeResponse
 */
export interface BillingListSubscriptionsWithinRangeResponse {
    /**
     * 
     * @type {number}
     * @memberof BillingListSubscriptionsWithinRangeResponse
     */
    'status': BillingListSubscriptionsWithinRangeResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingListSubscriptionsWithinRangeResponse
     */
    'error': BillingListSubscriptionsWithinRangeResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingListSubscriptionsWithinRangeResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof BillingListSubscriptionsWithinRangeResponse
     */
    'invalid'?: BillingListSubscriptionsWithinRangeResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof BillingListSubscriptionsWithinRangeResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type BillingListSubscriptionsWithinRangeResponseStatusEnum = 400
type BillingListSubscriptionsWithinRangeResponseErrorEnum = 'Bad Request'
type BillingListSubscriptionsWithinRangeResponseInvalidEnum = 'body' | 'path' | 'query'


