/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetActiveSubscription403Response
 */
export interface BillingGetActiveSubscription403Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetActiveSubscription403Response
     */
    'status': BillingGetActiveSubscription403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetActiveSubscription403Response
     */
    'error': BillingGetActiveSubscription403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetActiveSubscription403Response
     */
    'message': string;
}

type BillingGetActiveSubscription403ResponseStatusEnum = 403
type BillingGetActiveSubscription403ResponseErrorEnum = 'Forbidden'


