/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetInvoicePdf500Response
 */
export interface BillingGetInvoicePdf500Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetInvoicePdf500Response
     */
    'status': BillingGetInvoicePdf500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetInvoicePdf500Response
     */
    'error': BillingGetInvoicePdf500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetInvoicePdf500Response
     */
    'message': string;
}

type BillingGetInvoicePdf500ResponseStatusEnum = 500
type BillingGetInvoicePdf500ResponseErrorEnum = 'Internal Server Error'


