/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface BillingGetSpecificSubscriptionResponse
 */
export interface BillingGetSpecificSubscriptionResponse {
    /**
     * 
     * @type {number}
     * @memberof BillingGetSpecificSubscriptionResponse
     */
    'status': BillingGetSpecificSubscriptionResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetSpecificSubscriptionResponse
     */
    'error': BillingGetSpecificSubscriptionResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetSpecificSubscriptionResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof BillingGetSpecificSubscriptionResponse
     */
    'invalid'?: BillingGetSpecificSubscriptionResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof BillingGetSpecificSubscriptionResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type BillingGetSpecificSubscriptionResponseStatusEnum = 400
type BillingGetSpecificSubscriptionResponseErrorEnum = 'Bad Request'
type BillingGetSpecificSubscriptionResponseInvalidEnum = 'body' | 'path' | 'query'


