/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetSpecificInvoice404Response
 */
export interface BillingGetSpecificInvoice404Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetSpecificInvoice404Response
     */
    'status': BillingGetSpecificInvoice404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetSpecificInvoice404Response
     */
    'error': BillingGetSpecificInvoice404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetSpecificInvoice404Response
     */
    'message': string;
}

type BillingGetSpecificInvoice404ResponseStatusEnum = 404
type BillingGetSpecificInvoice404ResponseErrorEnum = 'Not Found'


