/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetInvoicePdf404Response
 */
export interface BillingGetInvoicePdf404Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetInvoicePdf404Response
     */
    'status': BillingGetInvoicePdf404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetInvoicePdf404Response
     */
    'error': BillingGetInvoicePdf404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetInvoicePdf404Response
     */
    'message': string;
}

type BillingGetInvoicePdf404ResponseStatusEnum = 404
type BillingGetInvoicePdf404ResponseErrorEnum = 'Not Found'


