/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetSpecificSubscription401Response
 */
export interface BillingGetSpecificSubscription401Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetSpecificSubscription401Response
     */
    'status': BillingGetSpecificSubscription401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetSpecificSubscription401Response
     */
    'error': BillingGetSpecificSubscription401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetSpecificSubscription401Response
     */
    'message': string;
}

type BillingGetSpecificSubscription401ResponseStatusEnum = 401
type BillingGetSpecificSubscription401ResponseErrorEnum = 'Unauthorized'


