/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BillingGetSpecificInvoice500Response
 */
export interface BillingGetSpecificInvoice500Response {
    /**
     * 
     * @type {number}
     * @memberof BillingGetSpecificInvoice500Response
     */
    'status': BillingGetSpecificInvoice500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BillingGetSpecificInvoice500Response
     */
    'error': BillingGetSpecificInvoice500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BillingGetSpecificInvoice500Response
     */
    'message': string;
}

type BillingGetSpecificInvoice500ResponseStatusEnum = 500
type BillingGetSpecificInvoice500ResponseErrorEnum = 'Internal Server Error'


