/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrowsersEstablishConnection500Response
 */
export interface BrowsersEstablishConnection500Response {
    /**
     * 
     * @type {number}
     * @memberof BrowsersEstablishConnection500Response
     */
    'status': BrowsersEstablishConnection500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BrowsersEstablishConnection500Response
     */
    'error': BrowsersEstablishConnection500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BrowsersEstablishConnection500Response
     */
    'message': string;
}

type BrowsersEstablishConnection500ResponseStatusEnum = 500
type BrowsersEstablishConnection500ResponseErrorEnum = 'Internal Server Error'


