/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface BrowsersEstablishConnectionResponse
 */
export interface BrowsersEstablishConnectionResponse {
    /**
     * 
     * @type {number}
     * @memberof BrowsersEstablishConnectionResponse
     */
    'status': BrowsersEstablishConnectionResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BrowsersEstablishConnectionResponse
     */
    'error': BrowsersEstablishConnectionResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BrowsersEstablishConnectionResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof BrowsersEstablishConnectionResponse
     */
    'invalid'?: BrowsersEstablishConnectionResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof BrowsersEstablishConnectionResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type BrowsersEstablishConnectionResponseStatusEnum = 400
type BrowsersEstablishConnectionResponseErrorEnum = 'Bad Request'
type BrowsersEstablishConnectionResponseInvalidEnum = 'body' | 'path' | 'query'


