/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrowsersEstablishConnection401Response
 */
export interface BrowsersEstablishConnection401Response {
    /**
     * 
     * @type {number}
     * @memberof BrowsersEstablishConnection401Response
     */
    'status': BrowsersEstablishConnection401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BrowsersEstablishConnection401Response
     */
    'error': BrowsersEstablishConnection401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BrowsersEstablishConnection401Response
     */
    'message': string;
}

type BrowsersEstablishConnection401ResponseStatusEnum = 401
type BrowsersEstablishConnection401ResponseErrorEnum = 'Unauthorized'


