/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrowsersEstablishConnection403Response
 */
export interface BrowsersEstablishConnection403Response {
    /**
     * 
     * @type {number}
     * @memberof BrowsersEstablishConnection403Response
     */
    'status': BrowsersEstablishConnection403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BrowsersEstablishConnection403Response
     */
    'error': BrowsersEstablishConnection403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof BrowsersEstablishConnection403Response
     */
    'message': string;
}

type BrowsersEstablishConnection403ResponseStatusEnum = 403
type BrowsersEstablishConnection403ResponseErrorEnum = 'Forbidden'


