/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * Invoice ID
     * @type {string}
     * @memberof Invoice
     */
    'invId': string;
    /**
     * 
     * @type {any}
     * @memberof Invoice
     */
    'subId': any;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'status': InvoiceStatusEnum;
    /**
     * 
     * @type {any}
     * @memberof Invoice
     */
    'error': any;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'currency': string;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'amountDue': number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'amountPaid': number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'totalDiscount': number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'totalTax': number;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'billedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'stripeInvId': string;
    /**
     * 
     * @type {any}
     * @memberof Invoice
     */
    'stripeSubId': any;
    /**
     * 
     * @type {any}
     * @memberof Invoice
     */
    'stripeCusId': any;
}

type InvoiceStatusEnum = 'draft' | 'open' | 'void' | 'paid' | 'uncollectible'


