/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface KeySecret
 */
export interface KeySecret {
    /**
     * Key ID
     * @type {string}
     * @memberof KeySecret
     */
    'keyId': string;
    /**
     * 
     * @type {string}
     * @memberof KeySecret
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof KeySecret
     */
    'role': KeySecretRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof KeySecret
     */
    'lastFour': string;
    /**
     * 
     * @type {string}
     * @memberof KeySecret
     */
    'expiredAt': string;
    /**
     * 
     * @type {string}
     * @memberof KeySecret
     */
    'secret': string;
}

type KeySecretRoleEnum = 'member' | 'admin'


