/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface KeyPut
 */
export interface KeyPut {
    /**
     * 
     * @type {string}
     * @memberof KeyPut
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof KeyPut
     */
    'role': KeyPutRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof KeyPut
     */
    'expiredAt': string;
}

type KeyPutRoleEnum = 'member' | 'admin'


