/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface KeyPublic
 */
export interface KeyPublic {
    /**
     * Key ID
     * @type {string}
     * @memberof KeyPublic
     */
    'keyId': string;
    /**
     * 
     * @type {string}
     * @memberof KeyPublic
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof KeyPublic
     */
    'role': KeyPublicRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof KeyPublic
     */
    'lastFour': string;
    /**
     * 
     * @type {string}
     * @memberof KeyPublic
     */
    'expiredAt': string;
}

type KeyPublicRoleEnum = 'member' | 'admin'


