/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface KeyPost
 */
export interface KeyPost {
    /**
     * 
     * @type {string}
     * @memberof KeyPost
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof KeyPost
     */
    'role'?: KeyPostRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof KeyPost
     */
    'expiredAt'?: string;
}

type KeyPostRoleEnum = 'member' | 'admin'


