/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NotFoundError
 */
export interface NotFoundError {
    /**
     * 
     * @type {number}
     * @memberof NotFoundError
     */
    'status': NotFoundErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof NotFoundError
     */
    'error': NotFoundErrorErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof NotFoundError
     */
    'message': string;
}

type NotFoundErrorStatusEnum = 404
type NotFoundErrorErrorEnum = 'Not Found'


