/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OpenApiGetYamlSpec500Response
 */
export interface OpenApiGetYamlSpec500Response {
    /**
     * 
     * @type {number}
     * @memberof OpenApiGetYamlSpec500Response
     */
    'status': OpenApiGetYamlSpec500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OpenApiGetYamlSpec500Response
     */
    'error': OpenApiGetYamlSpec500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof OpenApiGetYamlSpec500Response
     */
    'message': string;
}

type OpenApiGetYamlSpec500ResponseStatusEnum = 500
type OpenApiGetYamlSpec500ResponseErrorEnum = 'Internal Server Error'


