/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentRequiredError
 */
export interface PaymentRequiredError {
    /**
     * 
     * @type {number}
     * @memberof PaymentRequiredError
     */
    'status': PaymentRequiredErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequiredError
     */
    'error': PaymentRequiredErrorErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof PaymentRequiredError
     */
    'message': string;
}

type PaymentRequiredErrorStatusEnum = 402
type PaymentRequiredErrorErrorEnum = 'Payment Required'


