/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProxyAuthenticationRequiredError
 */
export interface ProxyAuthenticationRequiredError {
    /**
     * 
     * @type {number}
     * @memberof ProxyAuthenticationRequiredError
     */
    'status': ProxyAuthenticationRequiredErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ProxyAuthenticationRequiredError
     */
    'error': ProxyAuthenticationRequiredErrorErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ProxyAuthenticationRequiredError
     */
    'message': string;
}

type ProxyAuthenticationRequiredErrorStatusEnum = 407
type ProxyAuthenticationRequiredErrorErrorEnum = 'Proxy Authentication Required'


