/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ServiceUnavailableError
 */
export interface ServiceUnavailableError {
    /**
     * 
     * @type {number}
     * @memberof ServiceUnavailableError
     */
    'status': ServiceUnavailableErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceUnavailableError
     */
    'error': ServiceUnavailableErrorErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ServiceUnavailableError
     */
    'message': string;
}

type ServiceUnavailableErrorStatusEnum = 503
type ServiceUnavailableErrorErrorEnum = 'Service Unavailable'


