/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ServerCheckHealthStatus404Response
 */
export interface ServerCheckHealthStatus404Response {
    /**
     * 
     * @type {number}
     * @memberof ServerCheckHealthStatus404Response
     */
    'status': ServerCheckHealthStatus404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ServerCheckHealthStatus404Response
     */
    'error': ServerCheckHealthStatus404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ServerCheckHealthStatus404Response
     */
    'message': string;
}

type ServerCheckHealthStatus404ResponseStatusEnum = 404
type ServerCheckHealthStatus404ResponseErrorEnum = 'Not Found'


