/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ServerShowMetrics500Response
 */
export interface ServerShowMetrics500Response {
    /**
     * 
     * @type {number}
     * @memberof ServerShowMetrics500Response
     */
    'status': ServerShowMetrics500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ServerShowMetrics500Response
     */
    'error': ServerShowMetrics500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof ServerShowMetrics500Response
     */
    'message': string;
}

type ServerShowMetrics500ResponseStatusEnum = 500
type ServerShowMetrics500ResponseErrorEnum = 'Internal Server Error'


