/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * Subscription ID
     * @type {string}
     * @memberof Subscription
     */
    'subId': string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'tier': SubscriptionTierEnum;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'status': SubscriptionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'currency': string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'periodUnit': SubscriptionPeriodUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    'periodCount': number;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'periodStartsAt': string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'periodEndsAt': string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'anchoredAt': string;
    /**
     * 
     * @type {any}
     * @memberof Subscription
     */
    'canceledAt': any;
    /**
     * 
     * @type {any}
     * @memberof Subscription
     */
    'resumedAt': any;
    /**
     * 
     * @type {any}
     * @memberof Subscription
     */
    'pausedAt': any;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'stripeSubId': string;
    /**
     * 
     * @type {any}
     * @memberof Subscription
     */
    'stripeCusId': any;
}

type SubscriptionTierEnum = 'hobby' | 'business' | 'enterprise'
type SubscriptionStatusEnum = 'incomplete' | 'incomplete_expired' | 'active' | 'trialing' | 'past_due' | 'unpaid' | 'canceled' | 'paused'
type SubscriptionPeriodUnitEnum = 'day' | 'week' | 'month' | 'year'


