/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TooManyRequestsError
 */
export interface TooManyRequestsError {
    /**
     * 
     * @type {number}
     * @memberof TooManyRequestsError
     */
    'status': TooManyRequestsErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TooManyRequestsError
     */
    'error': TooManyRequestsErrorErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof TooManyRequestsError
     */
    'message': string;
}

type TooManyRequestsErrorStatusEnum = 429
type TooManyRequestsErrorErrorEnum = 'Too Many Requests'


