/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetRequestData403Response
 */
export interface UsageGetRequestData403Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetRequestData403Response
     */
    'status': UsageGetRequestData403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetRequestData403Response
     */
    'error': UsageGetRequestData403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetRequestData403Response
     */
    'message': string;
}

type UsageGetRequestData403ResponseStatusEnum = 403
type UsageGetRequestData403ResponseErrorEnum = 'Forbidden'


