/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageEvent
 */
export interface UsageEvent {
    /**
     * 
     * @type {string}
     * @memberof UsageEvent
     */
    'usageEventId': string;
    /**
     * 
     * @type {string}
     * @memberof UsageEvent
     */
    'usageSessionId': string;
    /**
     * 
     * @type {string}
     * @memberof UsageEvent
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof UsageEvent
     */
    'status': UsageEventStatusEnum;
    /**
     * 
     * @type {any}
     * @memberof UsageEvent
     */
    'data'?: any;
    /**
     * 
     * @type {string}
     * @memberof UsageEvent
     */
    'sentAt': string;
    /**
     * 
     * @type {string}
     * @memberof UsageEvent
     */
    'createdAt': string;
    /**
     * UsageSession ID
     * @type {string}
     * @memberof UsageEvent
     */
    'sessionId': string;
    /**
     * UsageEvent ID
     * @type {string}
     * @memberof UsageEvent
     */
    'eventId': string;
}

type UsageEventStatusEnum = 'pending' | 'success' | 'failure'


