/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface UsageGetRequestDataResponse
 */
export interface UsageGetRequestDataResponse {
    /**
     * 
     * @type {number}
     * @memberof UsageGetRequestDataResponse
     */
    'status': UsageGetRequestDataResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetRequestDataResponse
     */
    'error': UsageGetRequestDataResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetRequestDataResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof UsageGetRequestDataResponse
     */
    'invalid'?: UsageGetRequestDataResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof UsageGetRequestDataResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type UsageGetRequestDataResponseStatusEnum = 400
type UsageGetRequestDataResponseErrorEnum = 'Bad Request'
type UsageGetRequestDataResponseInvalidEnum = 'body' | 'path' | 'query'


