/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetRequestData401Response
 */
export interface UsageGetRequestData401Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetRequestData401Response
     */
    'status': UsageGetRequestData401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetRequestData401Response
     */
    'error': UsageGetRequestData401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetRequestData401Response
     */
    'message': string;
}

type UsageGetRequestData401ResponseStatusEnum = 401
type UsageGetRequestData401ResponseErrorEnum = 'Unauthorized'


