/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetSessionRange403Response
 */
export interface UsageGetSessionRange403Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetSessionRange403Response
     */
    'status': UsageGetSessionRange403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetSessionRange403Response
     */
    'error': UsageGetSessionRange403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetSessionRange403Response
     */
    'message': string;
}

type UsageGetSessionRange403ResponseStatusEnum = 403
type UsageGetSessionRange403ResponseErrorEnum = 'Forbidden'


