/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageListAggregateAccountUsage500Response
 */
export interface UsageListAggregateAccountUsage500Response {
    /**
     * 
     * @type {number}
     * @memberof UsageListAggregateAccountUsage500Response
     */
    'status': UsageListAggregateAccountUsage500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageListAggregateAccountUsage500Response
     */
    'error': UsageListAggregateAccountUsage500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageListAggregateAccountUsage500Response
     */
    'message': string;
}

type UsageListAggregateAccountUsage500ResponseStatusEnum = 500
type UsageListAggregateAccountUsage500ResponseErrorEnum = 'Internal Server Error'


