/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface UsageGetSessionRangeResponse
 */
export interface UsageGetSessionRangeResponse {
    /**
     * 
     * @type {number}
     * @memberof UsageGetSessionRangeResponse
     */
    'status': UsageGetSessionRangeResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetSessionRangeResponse
     */
    'error': UsageGetSessionRangeResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetSessionRangeResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof UsageGetSessionRangeResponse
     */
    'invalid'?: UsageGetSessionRangeResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof UsageGetSessionRangeResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type UsageGetSessionRangeResponseStatusEnum = 400
type UsageGetSessionRangeResponseErrorEnum = 'Bad Request'
type UsageGetSessionRangeResponseInvalidEnum = 'body' | 'path' | 'query'


