/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetRequestData404Response
 */
export interface UsageGetRequestData404Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetRequestData404Response
     */
    'status': UsageGetRequestData404ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetRequestData404Response
     */
    'error': UsageGetRequestData404ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetRequestData404Response
     */
    'message': string;
}

type UsageGetRequestData404ResponseStatusEnum = 404
type UsageGetRequestData404ResponseErrorEnum = 'Not Found'


