/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageListRequestEvents403Response
 */
export interface UsageListRequestEvents403Response {
    /**
     * 
     * @type {number}
     * @memberof UsageListRequestEvents403Response
     */
    'status': UsageListRequestEvents403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageListRequestEvents403Response
     */
    'error': UsageListRequestEvents403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageListRequestEvents403Response
     */
    'message': string;
}

type UsageListRequestEvents403ResponseStatusEnum = 403
type UsageListRequestEvents403ResponseErrorEnum = 'Forbidden'


