/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetSessionRange401Response
 */
export interface UsageGetSessionRange401Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetSessionRange401Response
     */
    'status': UsageGetSessionRange401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetSessionRange401Response
     */
    'error': UsageGetSessionRange401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetSessionRange401Response
     */
    'message': string;
}

type UsageGetSessionRange401ResponseStatusEnum = 401
type UsageGetSessionRange401ResponseErrorEnum = 'Unauthorized'


