/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetEventData500Response
 */
export interface UsageGetEventData500Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetEventData500Response
     */
    'status': UsageGetEventData500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetEventData500Response
     */
    'error': UsageGetEventData500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetEventData500Response
     */
    'message': string;
}

type UsageGetEventData500ResponseStatusEnum = 500
type UsageGetEventData500ResponseErrorEnum = 'Internal Server Error'


