/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageListRequestEvents500Response
 */
export interface UsageListRequestEvents500Response {
    /**
     * 
     * @type {number}
     * @memberof UsageListRequestEvents500Response
     */
    'status': UsageListRequestEvents500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageListRequestEvents500Response
     */
    'error': UsageListRequestEvents500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageListRequestEvents500Response
     */
    'message': string;
}

type UsageListRequestEvents500ResponseStatusEnum = 500
type UsageListRequestEvents500ResponseErrorEnum = 'Internal Server Error'


