/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface UsageListAggregateAccountUsageResponse
 */
export interface UsageListAggregateAccountUsageResponse {
    /**
     * 
     * @type {number}
     * @memberof UsageListAggregateAccountUsageResponse
     */
    'status': UsageListAggregateAccountUsageResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageListAggregateAccountUsageResponse
     */
    'error': UsageListAggregateAccountUsageResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageListAggregateAccountUsageResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof UsageListAggregateAccountUsageResponse
     */
    'invalid'?: UsageListAggregateAccountUsageResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof UsageListAggregateAccountUsageResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type UsageListAggregateAccountUsageResponseStatusEnum = 400
type UsageListAggregateAccountUsageResponseErrorEnum = 'Bad Request'
type UsageListAggregateAccountUsageResponseInvalidEnum = 'body' | 'path' | 'query'


