/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageBucket
 */
export interface UsageBucket {
    /**
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    'usageBucketId': string;
    /**
     * 
     * @type {any}
     * @memberof UsageBucket
     */
    'keyId': any;
    /**
     * 
     * @type {any}
     * @memberof UsageBucket
     */
    'clerkOrgId': any;
    /**
     * 
     * @type {any}
     * @memberof UsageBucket
     */
    'clerkUserId': any;
    /**
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    'bucket': string;
    /**
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    'method': UsageBucketMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    'endpoint': string;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'credits': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'countSuccess': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'countFailure': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'durationSuccess': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'durationFailure': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'durationMin': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'durationMax': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'durationMean': number;
    /**
     * 
     * @type {number}
     * @memberof UsageBucket
     */
    'durationStd': number;
}

type UsageBucketMethodEnum = 'api' | 'ws'


