/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetSessionRange500Response
 */
export interface UsageGetSessionRange500Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetSessionRange500Response
     */
    'status': UsageGetSessionRange500ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetSessionRange500Response
     */
    'error': UsageGetSessionRange500ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetSessionRange500Response
     */
    'message': string;
}

type UsageGetSessionRange500ResponseStatusEnum = 500
type UsageGetSessionRange500ResponseErrorEnum = 'Internal Server Error'


