/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetEventData401Response
 */
export interface UsageGetEventData401Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetEventData401Response
     */
    'status': UsageGetEventData401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetEventData401Response
     */
    'error': UsageGetEventData401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetEventData401Response
     */
    'message': string;
}

type UsageGetEventData401ResponseStatusEnum = 401
type UsageGetEventData401ResponseErrorEnum = 'Unauthorized'


