/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageListRequestEvents401Response
 */
export interface UsageListRequestEvents401Response {
    /**
     * 
     * @type {number}
     * @memberof UsageListRequestEvents401Response
     */
    'status': UsageListRequestEvents401ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageListRequestEvents401Response
     */
    'error': UsageListRequestEvents401ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageListRequestEvents401Response
     */
    'message': string;
}

type UsageListRequestEvents401ResponseStatusEnum = 401
type UsageListRequestEvents401ResponseErrorEnum = 'Unauthorized'


