/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageGetEventData403Response
 */
export interface UsageGetEventData403Response {
    /**
     * 
     * @type {number}
     * @memberof UsageGetEventData403Response
     */
    'status': UsageGetEventData403ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetEventData403Response
     */
    'error': UsageGetEventData403ResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetEventData403Response
     */
    'message': string;
}

type UsageGetEventData403ResponseStatusEnum = 403
type UsageGetEventData403ResponseErrorEnum = 'Forbidden'


