/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadRequestErrorFieldsInner } from './bad-request-error-fields-inner';

/**
 * 
 * @export
 * @interface UsageGetEventDataResponse
 */
export interface UsageGetEventDataResponse {
    /**
     * 
     * @type {number}
     * @memberof UsageGetEventDataResponse
     */
    'status': UsageGetEventDataResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageGetEventDataResponse
     */
    'error': UsageGetEventDataResponseErrorEnum;
    /**
     * Suggestions for debugging the issue
     * @type {string}
     * @memberof UsageGetEventDataResponse
     */
    'message': string;
    /**
     * Where the validation error occurred
     * @type {string}
     * @memberof UsageGetEventDataResponse
     */
    'invalid'?: UsageGetEventDataResponseInvalidEnum;
    /**
     * Validation errors, when available
     * @type {Array<BadRequestErrorFieldsInner>}
     * @memberof UsageGetEventDataResponse
     */
    'fields'?: Array<BadRequestErrorFieldsInner>;
}

type UsageGetEventDataResponseStatusEnum = 400
type UsageGetEventDataResponseErrorEnum = 'Bad Request'
type UsageGetEventDataResponseInvalidEnum = 'body' | 'path' | 'query'


