/*
BrowserCat API

Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

The version of the OpenAPI document: 1.0.0
Contact: support@browsercat.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageListAggregateAccountUsageUserIdParameterAnyOf } from './usage-list-aggregate-account-usage-user-id-parameter-any-of';

/**
 * @type UsageListAggregateAccountUsageUserIdParameter
 * @export
 */
export type UsageListAggregateAccountUsageUserIdParameter = string | UsageListAggregateAccountUsageUserIdParameterAnyOf;


